# Generated by Django 5.2.11 on 2026-02-21 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig_id', models.CharField(help_text='Instagram Media ID', max_length=255, unique=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('media_type', models.CharField(blank=True, max_length=50, null=True)),
                ('media_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('permalink', models.URLField(blank=True, max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(help_text='Original creation time on Instagram')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig_id', models.CharField(help_text='Instagram Comment ID', max_length=255, unique=True)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='instagram_sync.post')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
