# Generated by Django 5.2.11 on 2026-02-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='permalink',
            field=models.TextField(blank=True, null=True),
        ),
    ]
